"""Generic code execution tool for the agent harness.

Lets the LLM generate and run Python (or other supported languages) inside a
sandboxed subprocess.  Useful for one-off analysis, visualization, UQ, GP,
custom post-processing, or any task where a dedicated tool would be too
restrictive.

The tool runs code in a subprocess with a timeout and only sees the provided
working directory.  Output files (plots, CSVs) saved to that directory are
returned to the agent.
"""

from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field

from huginn.privacy import redact_secrets
from huginn.security import (
    ContainerExecutor,
    SandboxConfig,
    SandboxError,
    SandboxExecutor,
    get_executor,
)
from huginn.security.restricted_python import RestrictedPythonError, validate_code
from huginn.tools.base import HuginnTool
from huginn.types import ToolContext, ToolResult
import logging
logger = logging.getLogger(__name__)


# v14 Task 9: 重活识别 heuristic
# ponytail: 启发式规则, 不做 AST 解析. 升级路径: ast.walk 精确判定 + LLM 估时.
_HEAVY_CSV_LIBS = ("pdfplumber", "PyPDF2", "fitz")


def _is_heavy_task(input_data) -> tuple[bool, str]:
    """识别重活: 返回 (is_heavy, reason).

    判据 (满足任一):
      - 代码 > 200 行
      - timeout > 60s
      - 含 PDF 解析库 (pdfplumber/PyPDF2/fitz)
      - pd.read_csv 且没用 chunksize (粗略认为会一把加载大表)
    """
    code = getattr(input_data, "code", "") or ""
    if len(code.splitlines()) > 200:
        return True, f"code length {len(code.splitlines())} > 200 lines"
    timeout = getattr(input_data, "timeout", 0) or 0
    if timeout > 60:
        return True, f"timeout {timeout}s > 60s"
    if any(lib in code for lib in _HEAVY_CSV_LIBS):
        return True, "PDF parsing detected"
    if "pd.read_csv" in code and "chunksize" not in code:
        return True, "large CSV load without chunksize"
    return False, ""



class CodeToolInput(BaseModel):
    action: Literal["execute", "analyze", "generate"] = Field(default="execute")
    code: str = Field(..., description="Code snippet to execute or analyze")
    language: Literal["python"] = Field(
        default="python", description="Programming language"
    )
    working_dir: str | None = Field(default=None)
    input_files: list[str] = Field(
        default_factory=list, description="Input files available to the code"
    )
    output_files: list[str] = Field(
        default_factory=list, description="Expected output file names to collect"
    )
    result_variable: str | None = Field(
        default=None, description="Variable to serialize and return"
    )
    timeout: float = Field(
        default=60.0, gt=0, le=1800, description="Execution timeout in seconds (max 1800 for training runs)"
    )
    self_check: str | None = Field(
        default=None,
        description="Optional assert-based check code run AFTER main code succeeds. "
        "Use to verify rubric requirements: 'assert tok.value_embed(torch.tensor([1.0])).shape[0]==d_value'. "
        "Failure returns success=False with the AssertionError message."
    )


class CodeTool(HuginnTool):
    """Execute LLM-generated code inside a sandboxed subprocess."""

    name = "code_tool"
    category = "core"
    description = (
        "Execute Python code generated by the agent. Useful for custom analysis, "
        "visualization, uncertainty quantification, Gaussian processes, or any "
        "task where a fixed tool is too restrictive. Runs in a sandbox with a "
        "timeout and returns stdout, stderr, saved files, and optional result variables."
    )
    input_schema = CodeToolInput

    def __init__(self, sandbox: SandboxExecutor | None = None) -> None:
        super().__init__()
        self.sandbox = sandbox or SandboxExecutor()

    def call(
        self, args: dict[str, Any], context: ToolContext | None = None
    ) -> ToolResult:
        input_data = CodeToolInput(**args)
        work_dir = (
            Path(input_data.working_dir) if input_data.working_dir else Path.cwd()
        )
        work_dir.mkdir(parents=True, exist_ok=True)

        # v14 Task 9: 重活识别 + 自动 dispatch 给 Support subagent
        # ponytail: 失败时降级到原行为 (直接执行), 不阻塞主流程.
        # 升级路径: dispatch 失败计数 → 熔断 Support 路径, 强制本地执行.
        if input_data.action == "execute":
            is_heavy, reason = _is_heavy_task(input_data)
            if is_heavy and os.environ.get("HUGINN_CORE_SUPPORT_PROTOCOL", "1") == "1":
                # v14 Task 13: PersistentTerminal 路径优先 — 长任务不被枪毙.
                from huginn.tools.persistent_terminal import (
                    resolve_persistent_terminal_flag,
                )
                if resolve_persistent_terminal_flag(None):
                    dispatched = _dispatch_to_support_persistent(
                        input_data.code, context, reason,
                    )
                    if dispatched is not None:
                        return dispatched
                else:
                    dispatched = _dispatch_to_support(input_data.code, context, reason)
                    if dispatched is not None:
                        return dispatched

        try:
            if input_data.action == "generate":
                return self._generate(input_data)
            if input_data.action == "analyze":
                return self._execute(
                    input_data, work_dir, analyze=True, context=context
                )
            return self._execute(input_data, work_dir, context=context)
        except Exception as e:
            return ToolResult(data=None, success=False, error=f"Code tool failed: {e}")

    def _generate(self, args: CodeToolInput) -> ToolResult:
        """Return the code without executing it (for review/modification)."""
        return ToolResult(
            data={
                "language": args.language,
                "code": args.code,
                "message": "Code generated but not executed.",
            },
            success=True,
        )

    def _execute(
        self,
        args: CodeToolInput,
        work_dir: Path,
        analyze: bool = False,
        context: ToolContext | None = None,
    ) -> ToolResult:
        if args.language != "python":
            return ToolResult(
                data=None,
                success=False,
                error=f"Language '{args.language}' not supported yet.",
            )

        try:
            validate_code(args.code)
        except RestrictedPythonError as exc:
            return ToolResult(
                data=None, success=False, error=f"Code security check failed: {exc}"
            )

        script_path = work_dir / "_code_tool_script.py"
        full_code = self._wrap_code(args.code, args.result_variable, analyze)
        script_path.write_text(full_code, encoding="utf-8")

        # Snapshot existing files to detect new outputs
        before_files = set(work_dir.iterdir())

        try:
            executor = get_executor()
        except SandboxError as exc:
            return ToolResult(
                data=None, success=False, error=f"Execution blocked: {exc}"
            )

        if isinstance(executor, ContainerExecutor):
            result = executor.run(
                ["python", script_path.name],
                cwd=work_dir,
                timeout=args.timeout,
                capture_output=True,
                text=True,
            )
        else:
            cfg = SandboxConfig(
                dry_run=False,
                allowed_executables=self.sandbox.config.allowed_executables
                | {"python", "python3"},
                default_timeout=args.timeout,
            )
            # sidecar 打包后 PATH 里可能没有 python, shutil.which 返回 None
            # fallback 到 sys.executable (当前解释器绝对路径), PyInstaller 环境也有效
            # 这样 sandbox._resolve_executable 能拿到真实路径, 不会抛 FileNotFoundError
            python_exe = (
                shutil.which("python")
                or shutil.which("python3")
                or sys.executable
                or "python"
            )
            result = self.sandbox.run(
                [python_exe, str(script_path)],
                cwd=work_dir,
                config=cfg,
                capture_output=True,
                text=True,
                timeout=args.timeout,
            )

        # Collect requested or auto-detected output files
        after_files = set(work_dir.iterdir())
        new_files = after_files - before_files
        output_paths: dict[str, str] = {}

        for name in args.output_files:
            path = work_dir / name
            if path.exists():
                output_paths[name] = str(path)

        for path in new_files:
            if path.is_file() and path.suffix.lower() in (
                ".png",
                ".jpg",
                ".jpeg",
                ".csv",
                ".json",
                ".txt",
                ".xyz",
                ".data",
            ):
                output_paths[path.name] = str(path)

        parsed_result = self._parse_result_marker(result.stdout)

        # 失败时附修复建议, 让 agent 知道下一步该做什么
        suggest = ""
        if not result.success:
            from huginn.tools.bash_tool import _suggest_fix
            suggest = _suggest_fix(result.returncode, result.stderr, result.stdout, ["python"])

        # 从 stdout 提取进度行 (loss/epoch/step/error), 让 agent 快速看训练曲线
        from huginn.tools.bash_tool import _extract_progress
        progress = _extract_progress(result.stdout)

        tool_result = ToolResult(
            data={
                "returncode": result.returncode,
                "stdout": result.stdout,
                "stderr": result.stderr,
                "result": parsed_result,
                "output_files": output_paths,
                "suggest_fix": suggest,
                "stream_progress": progress,
                "message": (
                    "Code executed successfully."
                    if result.success
                    else "Code execution failed; see stderr."
                ),
            },
            success=result.success,
        )

        # 主代码成功后跑 self_check (assert-based rubric 对照)
        # 失败返回 success=False + AssertionError 消息, agent 能看到具体哪条没过
        if result.success and args.self_check:
            check_result = self._run_self_check(args.self_check, work_dir, context)
            if check_result is not None:
                tool_result.data["self_check"] = check_result
                tool_result.success = False
                tool_result.data["message"] = f"Self-check FAILED: {check_result}"

        self._audit_execution(args, tool_result, context)
        return tool_result

    def _run_self_check(
        self, check_code: str, work_dir: Path, context: ToolContext | None
    ) -> str | None:
        """跑 agent 提供的 assert 代码, 返回失败消息或 None.

        主代码的变量在 __main__ 里, self_check 作为同一进程的 exec 跑,
        能访问主代码定义的类/函数/变量. AssertionError → 返回消息.
        其他异常 → 返回消息 (不算 pass). None = 通过.
        """
        check_script = work_dir / "_code_tool_selfcheck.py"
        # self_check 跑在独立脚本, import 主脚本拿变量
        # ponytail: 不在主脚本里 exec — 隔离崩溃, 主结果已存
        check_script.write_text(
            "import sys, json, importlib.util\n"
            "spec = importlib.util.spec_from_file_location('_main_code', '_code_tool_script.py')\n"
            "_mod = importlib.util.module_from_spec(spec)\n"
            "try:\n"
            "    spec.loader.exec_module(_mod)\n"
            f"    {check_code}\n"
            "    print('__SELFCHECK_PASS__')\n"
            "except AssertionError as e:\n"
            "    print('__SELFCHECK_FAIL__:' + str(e))\n"
            "except Exception as e:\n"
            "    print('__SELFCHECK_ERROR__:' + f'{type(e).__name__}: {e}')\n",
            encoding="utf-8",
        )
        try:
            r = self.sandbox.run(
                [sys.executable, str(check_script)],
                cwd=work_dir,
                config=SandboxConfig(
                    dry_run=False,
                    allowed_executables=self.sandbox.config.allowed_executables | {"python"},
                    default_timeout=30.0,
                ),
                capture_output=True,
                text=True,
                timeout=30.0,
            )
            for line in reversed(r.stdout.splitlines()):
                if line.startswith("__SELFCHECK_PASS__"):
                    return None
                if line.startswith("__SELFCHECK_FAIL__"):
                    return line[len("__SELFCHECK_FAIL__:"):]
                if line.startswith("__SELFCHECK_ERROR__"):
                    return line[len("__SELFCHECK_ERROR__:"):]
            return f"self-check produced no marker. stdout: {r.stdout[:500]}"
        except Exception as e:
            return f"self-check execution error: {e}"

    def _audit_execution(
        self,
        args: CodeToolInput,
        result: ToolResult,
        context: ToolContext | None,
    ) -> None:
        """Log code execution to the audit logger if one is available."""
        if context is None or context.audit_logger is None:
            return
        try:
            import json as _json

            output_data = (
                _json.dumps(result.data, default=str, sort_keys=True)
                if result.data
                else None
            )
            context.audit_logger.log(
                event_type="code_execution",
                actor="agent",
                action=self.name,
                details={
                    "language": args.language,
                    "success": result.success,
                    "timeout": args.timeout,
                    "returncode": (
                        result.data.get("returncode") if result.data else None
                    ),
                },
                input_data=redact_secrets(args.code),
                output_data=redact_secrets(output_data) if output_data else None,
            )
        except Exception:
            logger.debug("audit execution failed", exc_info=True)

    def _wrap_code(self, code: str, result_variable: str | None, analyze: bool) -> str:
        header = "# Code generated by huginn-agent code_tool\n"
        if analyze:
            header += (
                "# Analysis mode: input files are available in the working directory\n"
            )

        footer = "\n"
        footer += "import json\n"
        footer += "try:\n"
        if result_variable:
            footer += f"    _result_value = {result_variable}\n"
        else:
            footer += "    _result_value = None\n"
        footer += "    print('__CODE_TOOL_RESULT__:' + json.dumps(_result_value, default=str))\n"
        footer += "except Exception as _e:\n"
        footer += "    print('__CODE_TOOL_RESULT_ERROR__:' + str(_e))\n"

        return header + code + "\n" + footer

    def _parse_result_marker(self, stdout: str) -> Any:
        for line in reversed(stdout.splitlines()):
            if line.startswith("__CODE_TOOL_RESULT__:"):
                payload = line[len("__CODE_TOOL_RESULT__:") :]
                try:
                    return json.loads(payload)
                except json.JSONDecodeError:
                    return payload
            if line.startswith("__CODE_TOOL_RESULT_ERROR__:"):
                return {"error": line[len("__CODE_TOOL_RESULT_ERROR__:") :]}
        return None


def _dispatch_to_support(
    code: str,
    context: ToolContext | None,
    reason: str,
) -> ToolResult | None:
    """把 code_tool 重活 rewrite 为 subagent_tool dispatch.

    CodeTool.call 是 sync, SubagentTool.call 是 async — 用 run_async 桥接.
    返回 None 表示 dispatch 没成立 (context 缺 agent_factory 等), 调用方应降级.

    返回的 ToolResult 带 metadata={"dispatched_to_support": True, ...},
    rcb_runner 主循环看到后写 cochain_type="curl" trace entry.
    """
    # context 必须有 agent_factory 才能起子 agent, 没有就降级
    if context is None or getattr(context, "agent_factory", None) is None:
        logger.debug(
            "support dispatch skipped: no agent_factory in context (reason=%s)", reason
        )
        return None

    try:
        from huginn.tools.subagent_tool import SubagentTool
        from huginn.utils.async_bridge import run_async

        support_input = {
            "action": "dispatch",
            "spec_name": "support",
            "task": (
                "Execute this code in isolation and return a JSON finding "
                "with key results / evidence / limitations / artifacts.\n\n"
                f"{code}"
            ),
        }
        result = run_async(SubagentTool().call(support_input, context))
    except Exception as exc:
        logger.warning(
            "support dispatch failed, falling back to local execution: %s", exc
        )
        return None

    # v14 Task 10: Čech H¹ 一致性检查 — Support finding vs Core context (原 code 作为 proxy).
    # ponytail: 真正 Core context 拿不到, 用触发 dispatch 的 code 当 claim proxy.
    # 升级路径: 从 ToolContext.memory_manager 取最近 N 条 Core message 做 core_context.
    if result.success and isinstance(result.data, dict):
        finding = result.data.get("summary")
        if finding:
            from huginn.agents.subagent import (
                _check_finding_consistency,
                _write_support_rejection,
            )
            h1_zero, h1_reason = _check_finding_consistency(finding, code)
            result.metadata["h1_status"] = "zero" if h1_zero else "nonzero"
            result.metadata["h1_reason"] = h1_reason
            if not h1_zero:
                _write_support_rejection(context.workspace, finding, h1_reason, code)
                result.data = {
                    "summary": None,
                    "message": (
                        f"Support finding rejected: {h1_reason}. "
                        "Finding written to .huginn/support_rejections.jsonl for later review."
                    ),
                }
                result.metadata["h1_obstruction"] = True
                result.metadata["rejection_reason"] = h1_reason

    # 给结果打标, 让 rcb_runner 主循环写 curl trace entry
    result.metadata["dispatched_to_support"] = True
    result.metadata["dispatch_reason"] = reason
    return result


def _dispatch_to_support_persistent(
    code: str,
    context: ToolContext | None,
    reason: str,
) -> ToolResult | None:
    """v14 Task 13: PersistentTerminal 路径 — 启 session 跑原 code, 立即返回.

    不等 Support 完成就返回 session_id, Core 通过 poll_support_session 续轮.
    返回 None 表示没法启动 session (workspace 解析失败等), 调用方降级.

    ponytail: cmd 用 [python, -u, -c, code] 强制 unbuffered, 否则 Windows
    pipe 模式下 print 会 block-buffer, read 拿不到 incremental output.
    升级路径: 跑 SubagentDispatch dispatch 而非裸 code, 让 Support subagent
    生成结构化 finding. 当前先跑裸 code, code 自己负责 print finding JSON.
    """
    workspace = None
    if context is not None and getattr(context, "workspace", None):
        workspace = str(context.workspace)
    elif context is not None and getattr(context, "session_id", None):
        # session_id 通常映射到 workspace/<session_id>/, 兜底用 cwd
        workspace = str(Path.cwd())

    try:
        from huginn.tools.persistent_terminal import get_default_terminal

        terminal = get_default_terminal()
        # -u 强制 stdout/stderr unbuffered, 非 PTY 模式下也能读到 print 输出
        cmd = [sys.executable, "-u", "-c", code]
        session_id = terminal.start(cmd, cwd=workspace)
    except Exception as exc:
        logger.warning(
            "PersistentTerminal dispatch failed, falling back: %s", exc
        )
        return None

    result = ToolResult(
        data={
            "session_id": session_id,
            "status": "started",
            "summary": None,
            "message": (
                f"Support task started in persistent session {session_id}. "
                "Use poll_support_session(session_id) to read incremental output."
            ),
        },
        success=True,
    )
    result.metadata["dispatched_to_support"] = True
    result.metadata["dispatched_via_persistent_terminal"] = True
    result.metadata["session_id"] = session_id
    result.metadata["dispatch_reason"] = reason
    return result


def self_check_v14_task9() -> None:
    """v14 Task 9: 重活识别 self-check.

    不调真实 SubagentTool (要 agent_factory), 只验 _is_heavy_task 判据.
    """
    # 250 行代码 → 重活
    long_code = "\n".join(f"x{i} = {i}" for i in range(250))
    inp = type("In", (), {"code": long_code, "timeout": 30})()
    is_heavy, reason = _is_heavy_task(inp)
    assert is_heavy, "250 行代码应识别为重活"
    assert "200 lines" in reason, f"reason 不对: {reason}"

    # PDF 解析 → 重活
    inp = type(
        "In",
        (),
        {
            "code": "import pdfplumber\nwith pdfplumber.open('a.pdf') as pdf:\n  pass",
            "timeout": 30,
        },
    )()
    is_heavy, reason = _is_heavy_task(inp)
    assert is_heavy and "PDF" in reason, f"PDF 解析应识别为重活, got {reason}"

    # 大 CSV 无 chunksize → 重活
    inp = type(
        "In", (), {"code": "import pandas as pd\ndf = pd.read_csv('big.csv')", "timeout": 30}
    )()
    is_heavy, reason = _is_heavy_task(inp)
    assert is_heavy and "CSV" in reason, f"大 CSV 应识别为重活, got {reason}"

    # 大 CSV 有 chunksize → 不是重活
    inp = type(
        "In",
        (),
        {"code": "import pandas as pd\nfor c in pd.read_csv('big.csv', chunksize=1000):\n  pass", "timeout": 30},
    )()
    is_heavy, _ = _is_heavy_task(inp)
    assert not is_heavy, "chunksize 不应识别为重活"

    # timeout > 60 → 重活
    inp = type("In", (), {"code": "print('hi')", "timeout": 120})()
    is_heavy, reason = _is_heavy_task(inp)
    assert is_heavy and "timeout" in reason, f"长 timeout 应识别为重活, got {reason}"

    # 短代码 + 短 timeout → 不是重活
    inp = type("In", (), {"code": "print('hello')", "timeout": 30})()
    is_heavy, _ = _is_heavy_task(inp)
    assert not is_heavy, "短代码不应识别为重活"

    print("[CHECK v14 Task 9] heavy task detection OK")


if __name__ == "__main__":
    self_check_v14_task9()
