"""HUGINN_* 环境变量的单一权威声明 (配置面的声明层).

为什么需要: 配置面此前散在 145 个文件、385 个变量上 —— 每个裸读点各自带
默认值, 无统一 schema, 无类型, 新变量可静默膨胀, 死变量无人回收. 本模块把
"配置面"收成**一处声明**: 每个 `HUGINN_*` 在此登记一次 (类型 / 权威默认值 /
作用域 / 状态), 读点改用 :mod:`huginn.env_access` 的类型化访问器取值.

本文件是配置面的**单一权威源** (single source of truth): 默认值只在这里声明一
次, 不再在每个读点重复. `tests/test_env_surface_governance.py` 强制以下不变量:

1. 代码里出现的每个 `HUGINN_*` 必须已在此声明 (拦截静默新增);
2. 每条声明必须仍被代码引用 (拦截死声明);
3. 声明的默认值必须与代码里最常见的默认值一致 (拦截默认漂移);
4. 裸 `os.environ` 读点数只减不增 (棘轮, 逼配置面收敛).

字段:
    type:    str|int|float|bool|json —— 值解析方式
    default: 权威默认值 (字符串形式; 空串 = 无默认)
    scope:   deployment(部署相关: 凭证/路径/模型) | feature(开关)
             | tuning(数值调参) | internal(内部常量) | legacy(迁移残余)
    status:  live | deprecated(旧变量名, 仅为向后兼容保留)

改本文件后跑 `python -m huginn.cli.config_audit` 复核; 新增变量必须先登记,
再在代码里经 env_access 读取 —— 不允许再出现未经声明的裸读.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EnvSpec:
    """单个 ``HUGINN_*`` 变量的权威声明."""

    type: str
    default: str
    scope: str
    status: str = "live"


# 单一权威声明表 (按作用域分组, 组内按名排序).
SCHEMA: dict[str, EnvSpec] = {
    # ---- deployment (71) --------------------------------------------
    "HUGINN_ADMIN_API_KEY": EnvSpec("str", "", "deployment"),
    "HUGINN_ALERT_WEBHOOK_URL": EnvSpec("str", "", "deployment"),
    "HUGINN_API_KEY": EnvSpec("str", "", "deployment"),
    "HUGINN_ATOMWORLD_DATA_DIR": EnvSpec("str", "", "deployment"),
    "HUGINN_AUDIT_SIGNING_KEY": EnvSpec("str", "", "deployment"),
    "HUGINN_BANDIT_Q_PATH": EnvSpec("str", "", "deployment"),
    "HUGINN_BASE_URL": EnvSpec("str", "", "deployment"),
    "HUGINN_BING_API_KEY": EnvSpec("str", "", "deployment"),
    "HUGINN_BING_ENDPOINT": EnvSpec("str", "", "deployment"),
    "HUGINN_BOURBAKI_PATH": EnvSpec("str", "", "deployment"),
    "HUGINN_BRAVE_API_KEY": EnvSpec("str", "", "deployment"),
    "HUGINN_CACHE_DIR": EnvSpec("str", "", "deployment"),
    "HUGINN_CHECKPOINTER_PATH": EnvSpec("str", "", "deployment"),
    "HUGINN_CONSOLIDATE_MODEL": EnvSpec("str", "", "deployment"),
    "HUGINN_CONSOLIDATE_PROVIDER": EnvSpec("str", "deepseek", "deployment"),
    "HUGINN_CONTEXT_BUDGET_TOKENS": EnvSpec("int", "0", "deployment"),
    "HUGINN_CORE_API_KEY": EnvSpec("str", "", "deployment"),
    "HUGINN_CREDENTIAL_DB": EnvSpec("str", "", "deployment"),
    "HUGINN_CREDENTIAL_KEY_FILE": EnvSpec("str", "", "deployment"),
    "HUGINN_DEEPSEEK_OCR_PATH": EnvSpec("str", "", "deployment"),
    "HUGINN_EMBED_MODEL": EnvSpec("str", "", "deployment"),
    "HUGINN_ENCRYPTION_KEY": EnvSpec("str", "", "deployment"),
    "HUGINN_ENCRYPTION_PASSWORD": EnvSpec("str", "", "deployment"),
    "HUGINN_EZPROXY_DOMAINS": EnvSpec("str", "", "deployment"),
    "HUGINN_EZPROXY_PREFIX": EnvSpec("str", "", "deployment"),
    "HUGINN_FILE_READ_MAX_OUTPUT_TOKENS": EnvSpec("str", "", "deployment"),
    "HUGINN_HF_ENDPOINT": EnvSpec("str", "", "deployment"),
    "HUGINN_HPC_HOST": EnvSpec("str", "", "deployment"),
    "HUGINN_JEPA_EMBED_MODEL": EnvSpec("str", "", "deployment"),
    "HUGINN_JWT_SECRET": EnvSpec("str", "", "deployment"),
    "HUGINN_KB_CHUNKS_PATH": EnvSpec("str", "", "deployment"),
    "HUGINN_LOCAL_VISION_MODEL": EnvSpec("str", "", "deployment"),
    "HUGINN_MAX_CONTEXT_TOKENS": EnvSpec("str", "", "deployment"),
    "HUGINN_MAX_TOKENS": EnvSpec("str", "", "deployment"),
    "HUGINN_MAX_TOOL_OUTPUT_TOKENS": EnvSpec("int", "25000", "deployment"),
    "HUGINN_MCMC_CKPT_DIR": EnvSpec("str", "", "deployment"),
    "HUGINN_MEMORY_DIR": EnvSpec("str", "", "deployment"),
    "HUGINN_MODEL": EnvSpec("str", "", "deployment"),
    "HUGINN_MODELS": EnvSpec("str", "", "deployment"),
    "HUGINN_MODEL_TIER": EnvSpec("str", "full", "deployment"),
    "HUGINN_MP_API_KEY": EnvSpec("str", "", "deployment"),
    "HUGINN_OAUTH_TOKEN": EnvSpec("str", "", "deployment"),
    "HUGINN_OTEL_ENDPOINT": EnvSpec("str", "", "deployment"),
    "HUGINN_PERSONA_SYNC_DIR": EnvSpec("str", "", "deployment"),
    "HUGINN_PRM_MODEL": EnvSpec("str", "", "deployment"),
    "HUGINN_PRM_PROVIDER": EnvSpec("str", "", "deployment"),
    "HUGINN_PROFILE_MODEL": EnvSpec("str", "", "deployment"),
    "HUGINN_PROFILE_PROVIDER": EnvSpec("str", "deepseek", "deployment"),
    "HUGINN_PROVIDER": EnvSpec("str", "default", "deployment"),
    "HUGINN_RATE_LIMIT_TOKENS_PER_SECOND": EnvSpec("int", "5000", "deployment"),
    "HUGINN_RATE_LIMIT_TOKENS_PER_TURN": EnvSpec("int", "100000", "deployment"),
    "HUGINN_RCB_CROSS_TASK_DIR": EnvSpec("str", "", "deployment"),
    "HUGINN_REMOTE_WORK_DIR": EnvSpec("str", "", "deployment"),
    "HUGINN_SEARXNG_URL": EnvSpec("str", "", "deployment"),
    "HUGINN_SECRET_BACKEND": EnvSpec("str", "env", "deployment"),
    "HUGINN_SELF_MODEL": EnvSpec("int", "0", "deployment"),
    "HUGINN_SERVER_URL": EnvSpec("str", "", "deployment"),
    "HUGINN_SPECULATIVE_DRAFT_TOKENS": EnvSpec("int", "5", "deployment"),
    "HUGINN_SPECULATIVE_MODEL": EnvSpec("str", "", "deployment"),
    "HUGINN_STATE_REGISTRY_PATH": EnvSpec("str", "", "deployment"),
    "HUGINN_TELEMETRY_PATH": EnvSpec("str", "", "deployment"),
    "HUGINN_TOOL_COMPRESSION_MAX_TOKENS": EnvSpec("int", "8000", "deployment"),
    "HUGINN_TRANSCRIPT_DIR": EnvSpec("str", "", "deployment"),
    "HUGINN_VAULT_TOKEN": EnvSpec("str", "", "deployment"),
    "HUGINN_VISION_BASE_URL": EnvSpec("str", "", "deployment"),
    "HUGINN_VISION_MODEL": EnvSpec("str", "", "deployment"),
    "HUGINN_VISION_PROVIDER": EnvSpec("str", "", "deployment"),
    "HUGINN_WECOM_TOKEN": EnvSpec("str", "", "deployment"),
    "HUGINN_WETLAB_ENDPOINT": EnvSpec("str", "", "deployment"),
    "HUGINN_WM_TOKEN_BUDGET": EnvSpec("int", "8192", "deployment"),
    "HUGINN_WORKSPACE": EnvSpec("str", ".", "deployment"),
    # ---- feature (62) -----------------------------------------------
    "HUGINN_AUTO_APPROVE": EnvSpec("bool", "false", "feature"),
    "HUGINN_BUDGET_APPROVAL": EnvSpec("bool", "false", "feature"),
    "HUGINN_ENABLE_EXPLORATION": EnvSpec("bool", "true", "feature"),
    "HUGINN_ENCRYPT_RAG_DOCS": EnvSpec("bool", "true", "feature"),
    "HUGINN_ENCRYPT_RAG_META": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_ANTI_HACKING_REWARD": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_ASD_STE100": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_BANDIT_MDP": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_BELIEF_DARWIN": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_BELIEF_MODE_SWITCH": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_BELIEF_UPDATE": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_CLARIFICATION": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_COMMS_CONTRACT": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_COMPUTE_POLICY": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_CONTEXT_ROUTER": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_CRDT_BRANCH_MERGE": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_CRDT_MERGE": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_CURIOSITY_HINT": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_EXTERNAL_THINKING": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_EXTREME_DISPATCH": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_FTS_AUTO_REBUILD": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_HARNESS_ADOPTION_GATE": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_HARNESS_JOINT_OPTIMIZER": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_HARNESS_META_IMPROVER": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_HARNESS_OOD_HOLDOUT": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_HARNESS_PHASE_EVOLVE": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_HARNESS_PROMPT_PATCH": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_HARNESS_SIGNIFICANCE_GATE": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_HARNESS_WORKFLOW_EVOLUTION": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_HILS_ATTENTION": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_HYPOTHESIS_LLM_SEMANTIC": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_INTENT_SCOPE_REWARD": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_ISING_FRONTIER": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_ISING_RERANK": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_JEV_ENABLED": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_JEV_GUARDRAIL": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_JEV_TOOL_ROUTER": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_JSON_LOGS": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_LOOP_DETECTOR": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_MEMORY_TYPING": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_PERSISTENT_TERMINAL": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_PERSONALIZATION": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_PI_MODE": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_PRIVACY_BLOCK_ON_SECRETS": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_PRIVACY_LOCAL_ONLY": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_PRIVACY_OFF": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_PRIVACY_REDACT": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_PRIVACY_REDACT_SECRETS": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_PROMPT_CACHE_CONTROL": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_PROVENANCE": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_SANDBOX_NET_ISOLATION": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_SPECULATOR": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_SYSTEM_HEALTH_AUTO_FIX": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_SYSTEM_HEALTH_MONITOR": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_TASK_TOOL_ROUTER": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_TELEMETRY": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_THREE_CABIN": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_TOOL_CALL_ROUTER": EnvSpec("bool", "true", "feature"),
    "HUGINN_FEATURE_USE_ATOMWORLD": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_USE_COGNITIVE_MAP": EnvSpec("bool", "false", "feature"),
    "HUGINN_FEATURE_WORLD_MODEL": EnvSpec("bool", "true", "feature"),
    "HUGINN_PERSONA_AUTO_ROUTE": EnvSpec("bool", "true", "feature"),
    # ---- tuning (136) ------------------------------------------------
    "HUGINN_ACTION_HIST_MAX": EnvSpec("int", "1000", "tuning"),
    "HUGINN_ALIGNMENT_SURPRISE_TRIGGER": EnvSpec("int", "0", "tuning"),
    "HUGINN_AUTOLOOP_HUMAN_PAUSE": EnvSpec("int", "0", "tuning"),
    "HUGINN_AUTOLOOP_NO_PLUGINS": EnvSpec("int", "0", "tuning"),
    "HUGINN_AUTOLOOP_STREAMING": EnvSpec("int", "1", "tuning"),
    "HUGINN_AUTO_WAKE": EnvSpec("int", "1", "tuning"),
    "HUGINN_BELIEF_ENTROPY_FACT_CHECK": EnvSpec("int", "0", "tuning"),
    "HUGINN_BELIEF_ENTROPY_HIGH": EnvSpec("float", "0.7", "tuning"),
    "HUGINN_BELIEF_ENTROPY_LOW": EnvSpec("float", "0.3", "tuning"),
    "HUGINN_BLIND_RECONSTRUCTION": EnvSpec("int", "0", "tuning"),
    "HUGINN_BRANCH_INCUBATOR_DEPTH": EnvSpec("int", "2", "tuning"),
    "HUGINN_BRANCH_VALUE_PRM": EnvSpec("int", "1", "tuning"),
    "HUGINN_BUDGET_DEADLINE_UNIFIED": EnvSpec("int", "1", "tuning"),
    "HUGINN_BUDGET_EXPIRE_SEMANTICS": EnvSpec("int", "1", "tuning"),
    "HUGINN_CHECKPOINTER_MAX_MESSAGES": EnvSpec("int", "120", "tuning"),
    "HUGINN_CODEACT_MEM_CAP": EnvSpec("int", "2147483648", "tuning"),
    "HUGINN_CODELAB_REPAIR_ATTEMPTS": EnvSpec("int", "3", "tuning"),
    "HUGINN_CODELAB_TIMEOUT_S": EnvSpec("int", "600", "tuning"),
    "HUGINN_CODER_MAX_ITER": EnvSpec("int", "50", "tuning"),
    "HUGINN_COEVOLUTION": EnvSpec("int", "0", "tuning"),
    "HUGINN_COGNITIVE_LLM_DECIDER": EnvSpec("int", "1", "tuning"),
    "HUGINN_COMPLETION_CHECK_INTERVAL": EnvSpec("int", "10", "tuning"),
    "HUGINN_CONTEXT_MAX_MESSAGES": EnvSpec("int", "60", "tuning"),
    "HUGINN_CORE_SUPPORT_PROTOCOL": EnvSpec("int", "1", "tuning"),
    "HUGINN_DARWIN_LLM_EVAL": EnvSpec("int", "0", "tuning"),
    "HUGINN_DARWIN_LLM_INTERVAL": EnvSpec("int", "5", "tuning"),
    "HUGINN_DARWIN_STAGNATION_LIMIT": EnvSpec("int", "5", "tuning"),
    "HUGINN_EM_RECALL_TOP_K": EnvSpec("int", "5", "tuning"),
    "HUGINN_ENABLE_AGENT_COLLAB": EnvSpec("int", "0", "tuning"),
    "HUGINN_ENFORCE_WRITE_CAPABILITY": EnvSpec("int", "1", "tuning"),
    "HUGINN_EPISODIC_REPLAY": EnvSpec("int", "0", "tuning"),
    "HUGINN_FAILURE_INVERSION": EnvSpec("int", "0", "tuning"),
    "HUGINN_HARNESS_GATES": EnvSpec("int", "0", "tuning"),
    "HUGINN_HEALTH_MONITOR": EnvSpec("int", "0", "tuning"),
    "HUGINN_HINT_COORDINATOR": EnvSpec("int", "1", "tuning"),
    "HUGINN_HTTP_QPS": EnvSpec("int", "5", "tuning"),
    "HUGINN_INHERIT_STABLE_PRINCIPLES": EnvSpec("int", "1", "tuning"),
    "HUGINN_ITER_HIST_MAX": EnvSpec("int", "50", "tuning"),
    "HUGINN_KEEP_ROOT_N": EnvSpec("int", "2", "tuning"),
    "HUGINN_KG_DEPTH": EnvSpec("int", "1", "tuning"),
    "HUGINN_KG_TOP_K": EnvSpec("int", "10", "tuning"),
    "HUGINN_LITERATURE_TIMEOUT": EnvSpec("int", "20", "tuning"),
    "HUGINN_LLM_LIKELIHOOD": EnvSpec("int", "0", "tuning"),
    "HUGINN_LLM_LIKELIHOOD_INTERVAL": EnvSpec("int", "5", "tuning"),
    "HUGINN_LLM_REQUEST_TIMEOUT": EnvSpec("int", "120", "tuning"),
    "HUGINN_LOCAL_ONLY": EnvSpec("int", "0", "tuning"),
    "HUGINN_LOCAL_VISION_TIMEOUT": EnvSpec("int", "20", "tuning"),
    "HUGINN_LOCAL_VISION_TTL": EnvSpec("float", "2.0", "tuning"),
    "HUGINN_LOOP_LIGHT_ON_TRACK": EnvSpec("int", "1", "tuning"),
    "HUGINN_LOOP_ROLLBACK": EnvSpec("int", "1", "tuning"),
    "HUGINN_MAX_BRANCHES": EnvSpec("int", "5", "tuning"),
    "HUGINN_MAX_CONCURRENT_SUBAGENTS": EnvSpec("int", "3", "tuning"),
    "HUGINN_MAX_CONSECUTIVE_FAILURES": EnvSpec("int", "20", "tuning"),
    "HUGINN_MAX_HEAVY_CONCURRENT": EnvSpec("int", "2", "tuning"),
    "HUGINN_MAX_LIGHT_CONCURRENT": EnvSpec("int", "8", "tuning"),
    "HUGINN_MAX_PIVOTS": EnvSpec("int", "10", "tuning"),
    "HUGINN_MAX_REFINES": EnvSpec("int", "20", "tuning"),
    "HUGINN_MAX_TOOL_CALLS": EnvSpec("int", "15", "tuning"),
    "HUGINN_MAX_TOOL_CALLS_PER_TOOL": EnvSpec("int", "5", "tuning"),
    "HUGINN_MCMC_ALIGNMENT": EnvSpec("int", "0", "tuning"),
    "HUGINN_MCMC_ALIGNMENT_TEMPERATURE": EnvSpec("float", "1.0", "tuning"),
    "HUGINN_MCMC_ANCHOR": EnvSpec("int", "1", "tuning"),
    "HUGINN_MCMC_ANCHOR_LAMBDA": EnvSpec("float", "0.1", "tuning"),
    "HUGINN_MCMC_CHAINS": EnvSpec("int", "4", "tuning"),
    "HUGINN_MCMC_CHECKPOINT_INTERVAL": EnvSpec("int", "10000", "tuning"),
    "HUGINN_MCMC_GLOBAL_PROPOSAL": EnvSpec("float", "0.3", "tuning"),
    "HUGINN_MCMC_GRAMIAN": EnvSpec("int", "1", "tuning"),
    "HUGINN_MCMC_GRAMIAN_K": EnvSpec("int", "1", "tuning"),
    "HUGINN_MCMC_HAPTIC": EnvSpec("int", "1", "tuning"),
    "HUGINN_MCMC_HAPTIC_TEMPERATURE": EnvSpec("float", "1.0", "tuning"),
    "HUGINN_MCMC_INTERVAL": EnvSpec("int", "5", "tuning"),
    "HUGINN_MCMC_NO_ANNEAL": EnvSpec("int", "0", "tuning"),
    "HUGINN_MCMC_PARALLEL": EnvSpec("int", "1", "tuning"),
    "HUGINN_MCMC_SE3": EnvSpec("int", "0", "tuning"),
    "HUGINN_MCMC_SE3_ANGLE_SIGMA": EnvSpec("float", "30.0", "tuning"),
    "HUGINN_MCMC_SEED": EnvSpec("int", "42", "tuning"),
    "HUGINN_MCMC_STEPS": EnvSpec("int", "7000000", "tuning"),
    "HUGINN_MCMC_T_HIGH": EnvSpec("int", "10", "tuning"),
    "HUGINN_MEMORY_CLUSTER": EnvSpec("int", "0", "tuning"),
    "HUGINN_MEMORY_DECAY_INTERVAL_TURNS": EnvSpec("int", "0", "tuning"),
    "HUGINN_MEMORY_DECAY_PRUNE_THRESHOLD": EnvSpec("float", "0.15", "tuning"),
    "HUGINN_MULTI_AGENT": EnvSpec("int", "0", "tuning"),
    "HUGINN_NOVELTY_EVAL": EnvSpec("int", "0", "tuning"),
    "HUGINN_OTEL_BATCH_SIZE": EnvSpec("int", "32", "tuning"),
    "HUGINN_OTEL_INTERVAL": EnvSpec("int", "5", "tuning"),
    "HUGINN_PASTE_OFFLOAD": EnvSpec("int", "1", "tuning"),
    "HUGINN_PERSISTENT_GOAL_MODE": EnvSpec("int", "0", "tuning"),
    "HUGINN_PERSONA_AUTO_ROUTE_THRESHOLD": EnvSpec("float", "0.3", "tuning"),
    "HUGINN_PER_HYP_BUDGET": EnvSpec("int", "0", "tuning"),
    "HUGINN_PLAN_AUTO_CONFIRM": EnvSpec("int", "0", "tuning"),
    "HUGINN_PMK_INJECT": EnvSpec("int", "0", "tuning"),
    "HUGINN_PM_C_MIN": EnvSpec("float", "0.2", "tuning"),
    "HUGINN_PRM_VERIFIER": EnvSpec("int", "0", "tuning"),
    "HUGINN_PROGRESSIVE_BUDGET_BY_REMAINING": EnvSpec("int", "1", "tuning"),
    "HUGINN_PROVENANCE_ENABLED": EnvSpec("int", "1", "tuning"),
    "HUGINN_PRT_LEVEL1": EnvSpec("int", "0", "tuning"),
    "HUGINN_RATE_LIMIT_ENABLED": EnvSpec("int", "1", "tuning"),
    "HUGINN_RATE_LIMIT_PER_MINUTE": EnvSpec("int", "0", "tuning"),
    "HUGINN_RATE_LIMIT_TOTAL_COST_USD": EnvSpec("float", "10.0", "tuning"),
    "HUGINN_RATE_LIMIT_WARNING_THRESHOLD": EnvSpec("float", "0.8", "tuning"),
    "HUGINN_RCB_CROSS_TASK": EnvSpec("int", "1", "tuning"),
    "HUGINN_RCB_EXEC_ITERS": EnvSpec("int", "20", "tuning"),
    "HUGINN_RCB_FORK_ENABLED": EnvSpec("int", "1", "tuning"),
    "HUGINN_RCB_FORK_K_MAX": EnvSpec("int", "3", "tuning"),
    "HUGINN_RCB_MAX_COMPLETE_REJECTIONS": EnvSpec("int", "3", "tuning"),
    "HUGINN_RCB_TIMEOUT": EnvSpec("int", "7200", "tuning"),
    "HUGINN_RECALL_NOISE_FLOOR": EnvSpec("float", "0.35", "tuning"),
    "HUGINN_RENAME_DEBT_LIMIT": EnvSpec("int", "8", "tuning"),
    "HUGINN_REPEAT_EXEC_HARD_STREAK": EnvSpec("int", "2", "tuning"),
    "HUGINN_RESTRICTED_PYTHON": EnvSpec("int", "1", "tuning"),
    "HUGINN_SELF_GOAL_SYNTHESIS": EnvSpec("int", "0", "tuning"),
    "HUGINN_SESSION_TTL_HOURS": EnvSpec("int", "24", "tuning"),
    "HUGINN_SKILL_ABSTRACTION": EnvSpec("int", "0", "tuning"),
    "HUGINN_SKILL_CONTEXT": EnvSpec("int", "0", "tuning"),
    "HUGINN_SKIP_SMOKE": EnvSpec("int", "0", "tuning"),
    "HUGINN_STALL_AS_ACTION": EnvSpec("int", "0", "tuning"),
    "HUGINN_STREAM_FALLBACK_RESUME": EnvSpec("int", "1", "tuning"),
    "HUGINN_STREAM_IDLE_TIMEOUT": EnvSpec("int", "60", "tuning"),
    "HUGINN_STRENGTH_SCHEDULE": EnvSpec("int", "1", "tuning"),
    "HUGINN_SURPRISE_HIST_CAP": EnvSpec("int", "200", "tuning"),
    "HUGINN_THREAD_POOL_SIZE": EnvSpec("int", "64", "tuning"),
    "HUGINN_TOOLUNIVERSE_ENABLED": EnvSpec("int", "0", "tuning"),
    "HUGINN_TRAJECTORY_PATTERN": EnvSpec("int", "0", "tuning"),
    "HUGINN_USE_COMPLETION_GATE": EnvSpec("int", "0", "tuning"),
    "HUGINN_USE_CROSS_DOMAIN": EnvSpec("int", "0", "tuning"),
    "HUGINN_USE_EVOLUTION_MANAGER": EnvSpec("int", "1", "tuning"),
    "HUGINN_USE_KNOWLEDGE_GRAPH": EnvSpec("int", "0", "tuning"),
    "HUGINN_USE_MENTAL_IMAGERY": EnvSpec("int", "0", "tuning"),
    "HUGINN_USE_MISI": EnvSpec("int", "0", "tuning"),
    "HUGINN_USE_UNIFIED_DECISION": EnvSpec("int", "0", "tuning"),
    "HUGINN_VALIDATE_FAIL_THRESHOLD": EnvSpec("float", "0.8", "tuning"),
    "HUGINN_VALIDATE_WINDOW": EnvSpec("int", "100", "tuning"),
    "HUGINN_WEB_SEARCH_TIMEOUT": EnvSpec("int", "15", "tuning"),
    "HUGINN_WM_SUMMARIZE_EVERY_N": EnvSpec("int", "5", "tuning"),
    "HUGINN_WS_MAX_CONNECTIONS": EnvSpec("int", "50", "tuning"),
    "HUGINN_WS_MAX_MSGS_PER_SEC": EnvSpec("int", "20", "tuning"),
    # ---- internal (91) ----------------------------------------------
    "HUGINN_AGENTS": EnvSpec("str", "", "internal"),
    "HUGINN_AINVOKE_TIMEOUT": EnvSpec("str", "", "internal"),
    "HUGINN_ALLOW_LOCAL_BASH": EnvSpec("str", "", "internal"),
    "HUGINN_ALLOW_POWERSHELL": EnvSpec("str", "", "internal"),
    "HUGINN_ALLOW_UNRESTRICTED_READ": EnvSpec("str", "", "internal"),
    "HUGINN_APPROVAL_MODE": EnvSpec("str", "", "internal"),
    "HUGINN_BENCHMARK_MODE_PROMPT": EnvSpec("str", "", "internal"),
    "HUGINN_BUDGET_MODE": EnvSpec("str", "cumulative", "internal"),
    "HUGINN_CI": EnvSpec("str", "", "internal"),
    "HUGINN_CODELAB_SCAFFOLD": EnvSpec("str", "", "internal"),
    "HUGINN_CODER_DONE_MARKER": EnvSpec("str", "", "internal"),
    "HUGINN_COMPACT_KIND": EnvSpec("str", "remote", "internal"),
    "HUGINN_COMPACT_STRATEGY": EnvSpec("str", "", "internal"),
    "HUGINN_COMPACT_THRESHOLD": EnvSpec("str", "", "internal"),
    "HUGINN_CONFIG_FILE": EnvSpec("str", "huginn.toml", "internal"),
    "HUGINN_CONTAINER_IMAGE": EnvSpec("str", "", "internal"),
    "HUGINN_CONTAINER_RUNTIME": EnvSpec("str", "none", "internal"),
    "HUGINN_CORS_ORIGINS": EnvSpec("str", "", "internal"),
    "HUGINN_CPU_HOUR_BUDGET": EnvSpec("str", "", "internal"),
    "HUGINN_CSM_SUBSET_MODE": EnvSpec("str", "", "internal"),
    "HUGINN_DEV_MODE": EnvSpec("str", "", "internal"),
    "HUGINN_DISABLE_WEB_SEARCH": EnvSpec("str", "", "internal"),
    "HUGINN_DOCKER_SANDBOX": EnvSpec("str", "", "internal"),
    "HUGINN_DOC_ENGINE": EnvSpec("str", "auto", "internal"),
    "HUGINN_ENABLE_SCIHUB": EnvSpec("str", "", "internal"),
    "HUGINN_ENCRYPTION_ENABLED": EnvSpec("str", "", "internal"),
    "HUGINN_ENCRYPTION_KEY_FILE": EnvSpec("str", "", "internal"),
    "HUGINN_ENCRYPT_CONFIG": EnvSpec("str", "", "internal"),
    "HUGINN_ENV": EnvSpec("str", "", "internal"),
    "HUGINN_EPISODIC_SHARD_INTERVAL": EnvSpec("str", "_DEFAULT_INTERVAL", "internal"),
    "HUGINN_EXECUTION_BACKEND": EnvSpec("str", "local", "internal"),
    "HUGINN_FALLBACK_STREAM_IDLE": EnvSpec("str", "", "internal"),
    "HUGINN_FILE_READ_MAX_SIZE_BYTES": EnvSpec("str", "", "internal"),
    "HUGINN_FP_DB": EnvSpec("str", "_DEFAULT_DB", "internal"),
    "HUGINN_FS_READ_MAX_SIZE_BYTES": EnvSpec("str", "", "internal"),
    "HUGINN_GOVERNANCE_DEFAULT_DECISION": EnvSpec("str", "deny", "internal"),
    "HUGINN_GPU_HOUR_BUDGET": EnvSpec("str", "", "internal"),
    "HUGINN_HARD_CHECKPOINT_PHASES": EnvSpec("str", "", "internal"),
    "HUGINN_HIDE_DOCS": EnvSpec("str", "", "internal"),
    "HUGINN_HUMAN_CHECKPOINT_PHASES": EnvSpec("str", "", "internal"),
    "HUGINN_JEPA_CORPUS": EnvSpec("str", "", "internal"),
    "HUGINN_KG_ENABLED": EnvSpec("str", "", "internal"),
    "HUGINN_LAZY_CLI": EnvSpec("str", "", "internal"),
    "HUGINN_LOG_LEVEL": EnvSpec("str", "", "internal"),
    "HUGINN_MAINTENANCE": EnvSpec("str", "", "internal"),
    "HUGINN_MAX_BODY_SIZE_MB": EnvSpec("str", "_DEFAULT_MAX_BODY_MB", "internal"),
    "HUGINN_MAX_FAILURES_BY_TYPE": EnvSpec("str", "", "internal"),
    "HUGINN_MCMC_MODE": EnvSpec("str", "", "internal"),
    "HUGINN_MCP_ALLOWED_COMMANDS": EnvSpec("str", "", "internal"),
    "HUGINN_MEMORY_DECAY_ENABLED": EnvSpec("str", "", "internal"),
    "HUGINN_NORMALIZE_ERRORS": EnvSpec("str", "", "internal"),
    "HUGINN_OCR_ENGINE": EnvSpec("str", "auto", "internal"),
    "HUGINN_OTEL_HEADERS": EnvSpec("str", "", "internal"),
    "HUGINN_OTEL_SERVICE_NAME": EnvSpec("str", "huginn", "internal"),
    "HUGINN_PASTE_OFFLOAD_THRESHOLD": EnvSpec("str", "", "internal"),
    "HUGINN_PERSISTENT_TERMINAL_TIMEOUT": EnvSpec("str", "", "internal"),
    "HUGINN_PERSONA": EnvSpec("str", "default", "internal"),
    "HUGINN_PERSONA_AUTO_SYNC": EnvSpec("str", "", "internal"),
    "HUGINN_PET_NAME": EnvSpec("str", "渡鸦", "internal"),
    "HUGINN_PET_PERSONALITY": EnvSpec("str", "cheerful", "internal"),
    "HUGINN_RAG_ENABLED": EnvSpec("str", "", "internal"),
    "HUGINN_RCB_BLOCKED_TOOLS": EnvSpec("str", "", "internal"),
    "HUGINN_RCB_DEADLINE": EnvSpec("str", "", "internal"),
    "HUGINN_REQUEST_TIMEOUT_SEC": EnvSpec("str", "_DEFAULT_TIMEOUT_SEC", "internal"),
    "HUGINN_ROOT_MARKERS": EnvSpec("str", "_DEFAULT_ROOT_MARKERS", "internal"),
    "HUGINN_SANDBOX_BLOCKED_PATHS": EnvSpec("str", "", "internal"),
    "HUGINN_SANDBOX_ISOLATE_NETWORK": EnvSpec("str", "", "internal"),
    "HUGINN_SANDBOX_MAX_CPU_SECONDS": EnvSpec("str", "", "internal"),
    "HUGINN_SANDBOX_MAX_FILE_BYTES": EnvSpec("str", "", "internal"),
    "HUGINN_SANDBOX_MAX_PROCESSES": EnvSpec("str", "", "internal"),
    "HUGINN_SANDBOX_RELAX": EnvSpec("str", "", "internal"),
    "HUGINN_SKIP_CSM": EnvSpec("str", "", "internal"),
    "HUGINN_SOBKO_HIERARCHICAL_INDEX": EnvSpec("str", "", "internal"),
    "HUGINN_SOBKO_TROUBLESHOOTING": EnvSpec("str", "", "internal"),
    "HUGINN_SPECULATIVE_ENABLED": EnvSpec("str", "", "internal"),
    "HUGINN_SPECULATOR_HISTORY": EnvSpec("str", "", "internal"),
    "HUGINN_STANDING_RULES": EnvSpec("str", "", "internal"),
    "HUGINN_STARTUP_DEADCODE": EnvSpec("str", "", "internal"),
    "HUGINN_STATE_BACKEND": EnvSpec("str", "", "internal"),
    "HUGINN_STE_MODE": EnvSpec("str", "agents", "internal"),
    "HUGINN_SWARM_DISTRIBUTED": EnvSpec("str", "", "internal"),
    "HUGINN_TEAM_MODE": EnvSpec("str", "", "internal"),
    "HUGINN_THINKING": EnvSpec("str", "high", "internal"),
    "HUGINN_TOOL_TIMEOUT": EnvSpec("str", "", "internal"),
    "HUGINN_TORCH_DEVICE": EnvSpec("str", "cpu", "internal"),
    "HUGINN_TRACE_SHARD_INTERVAL": EnvSpec("str", "", "internal"),
    "HUGINN_UNPAYWALL_EMAIL": EnvSpec("str", "", "internal"),
    "HUGINN_USE_DOCKER": EnvSpec("str", "", "internal"),
    "HUGINN_USE_RUST_SANDBOX": EnvSpec("str", "", "internal"),
    "HUGINN_VAULT_ADDR": EnvSpec("str", "", "internal"),
    "HUGINN_WM_SUMMARIZE": EnvSpec("str", "rule", "internal"),
    # ---- legacy (25) ------------------------------------------------
    "HUGINN_BANDIT_MDP": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_BELIEF_DARWIN": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_BELIEF_MODE_SWITCH": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_BELIEF_UPDATE": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_CONTEXT_ROUTER": EnvSpec("bool", "false", "legacy", status="deprecated"),
    "HUGINN_CRDT_BRANCH_MERGE": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_CRDT_MERGE": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_CURIOSITY_HINT": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_EXTREME_DISPATCH": EnvSpec("bool", "false", "legacy", status="deprecated"),
    "HUGINN_FTS_AUTO_REBUILD": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_HILS_ATTENTION": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_ISING_FRONTIER": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_ISING_RERANK": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_JSON_LOGS": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_PERSISTENT_TERMINAL": EnvSpec("bool", "false", "legacy", status="deprecated"),
    "HUGINN_PRIVACY_BLOCK_ON_SECRETS": EnvSpec("bool", "false", "legacy", status="deprecated"),
    "HUGINN_PRIVACY_REDACT_SECRETS": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_PROMPT_CACHE_CONTROL": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_TASK_TOOL_ROUTER": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_TELEMETRY_ENABLED": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_USE_ATOMWORLD": EnvSpec("bool", "false", "legacy", status="deprecated"),
    "HUGINN_USE_COGNITIVE_MAP": EnvSpec("bool", "false", "legacy", status="deprecated"),
    "HUGINN_USE_MEMORY_TYPING": EnvSpec("bool", "true", "legacy", status="deprecated"),
    "HUGINN_USE_THREE_CABIN": EnvSpec("bool", "false", "legacy", status="deprecated"),
    "HUGINN_WORLD_MODEL": EnvSpec("bool", "true", "legacy", status="deprecated"),
}


# 裸读站点棘轮基线 = 当前代码里字面量 HUGINN_* 读点总数.
# 治理测试断言实际值 <= 此数, 即只减不增; 迁移读点到 env_access 后应下调此数.
RAW_READ_BASELINE = 467


# 已知默认值分散: 同一变量在代码多处字面量默认值不一致 (双真值来源).
# 治理测试只允许此集合收窄, 不允许新增 —— 新增分散须先收敛读点再登记.
KNOWN_DEFAULT_DISPERSION: dict[str, tuple[str, ...]] = {
    "HUGINN_MCMC_HAPTIC": ("0", "1"),
}
