"""结构 I/O — 读结构 / 写 XYZ / 写 POSCAR.

ASE 可用时优先用 ase.io.read, 否则退到内置 XYZ 解析器.
写文件不依赖 ASE, 直接拼字符串, 方便临时目录调用.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    pass


def read_structure(src: str | dict) -> dict:
    """读结构, 返回 {atomic_numbers, positions, cell}.

    优先用 ASE 解析文件; ASE 不可用时支持内联 dict 和简单 XYZ.
    """
    if isinstance(src, dict):
        return {
            "atomic_numbers": list(src["atomic_numbers"]),
            "positions": np.asarray(src["positions"], dtype=float),
            "cell": (
                np.asarray(src["cell"], dtype=float)
                if src.get("cell") is not None
                else None
            ),
        }

    # 文件路径
    try:
        from ase.io import read

        atoms = read(src)
        return {
            "atomic_numbers": list(atoms.get_atomic_numbers()),
            "positions": np.asarray(atoms.get_positions(), dtype=float),
            "cell": (
                np.asarray(atoms.get_cell(), dtype=float)
                if atoms.pbc.any()
                else None
            ),
        }
    except ImportError:
        pass

    # 退回简单 XYZ 解析
    return read_xyz_fallback(src)


def read_xyz_fallback(path: str) -> dict:
    """无 ASE 时的 XYZ 简易解析器 (够 NEB 用)."""
    from collections import OrderedDict

    atomic_symbols_to_z = OrderedDict(
        [
            ("H", 1), ("He", 2), ("Li", 3), ("Be", 4), ("B", 5),
            ("C", 6), ("N", 7), ("O", 8), ("F", 9), ("Ne", 10),
            ("Na", 11), ("Mg", 12), ("Al", 13), ("Si", 14), ("P", 15),
            ("S", 16), ("Cl", 17), ("Ar", 18), ("K", 19), ("Ca", 20),
        ]
    )
    positions: list[list[float]] = []
    atomic_numbers: list[int] = []
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()
    n_atoms = int(lines[0].strip())
    for line in lines[2 : 2 + n_atoms]:
        parts = line.split()
        sym = parts[0]
        z = atomic_symbols_to_z.get(sym, 0)
        atomic_numbers.append(z)
        positions.append([float(parts[1]), float(parts[2]), float(parts[3])])
    return {
        "atomic_numbers": atomic_numbers,
        "positions": np.asarray(positions, dtype=float),
        "cell": None,
    }


def write_xyz(
    path: str,
    atomic_numbers: list[int],
    positions: np.ndarray,
    cell: np.ndarray | None,
) -> None:
    """写扩展 XYZ (含 Lattice 行, ASE 可读)."""
    z_to_sym = {
        1: "H", 2: "He", 3: "Li", 4: "Be", 5: "B", 6: "C", 7: "N",
        8: "O", 9: "F", 10: "Ne", 11: "Na", 12: "Mg", 13: "Al",
        14: "Si", 15: "P", 16: "S", 17: "Cl", 18: "Ar", 19: "K", 20: "Ca",
    }
    n = len(atomic_numbers)
    lines = [str(n), "generated by neb_tool"]
    if cell is not None:
        # 扩展 XYZ 第二行写 Lattice, ASE 能识别
        cell_flat = " ".join(f"{v:.10f}" for v in cell.ravel())
        lines[1] = f'Lattice="{cell_flat}" Properties=species:S:1:pos:R:3'
    for z, pos in zip(atomic_numbers, positions):
        sym = z_to_sym.get(int(z), "X")
        lines.append(
            f"{sym} {pos[0]:.10f} {pos[1]:.10f} {pos[2]:.10f}"
        )
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def write_poscar(
    path,
    atomic_numbers: list[int],
    positions: np.ndarray,
    cell: np.ndarray | None,
) -> None:
    """写一个最简 POSCAR (直接写, 不依赖 ASE)."""
    if cell is None:
        # 没晶胞就给个大方盒
        cell = np.eye(3) * 20.0
    scale = 1.0
    # 按原子种类分组
    from collections import OrderedDict

    grouped: OrderedDict[int, list[list[float]]] = OrderedDict()
    for z, pos in zip(atomic_numbers, positions):
        grouped.setdefault(int(z), []).append(pos.tolist())

    elements = list(grouped.keys())
    counts = [len(grouped[z]) for z in elements]
    z_to_sym = {
        1: "H", 6: "C", 7: "N", 8: "O", 14: "Si", 13: "Al", 26: "Fe",
        29: "Cu", 22: "Ti", 23: "V", 24: "Cr", 25: "Mn", 28: "Ni",
        30: "Zn", 11: "Na", 12: "Mg", 19: "K", 20: "Ca",
    }
    syms = [z_to_sym.get(z, "X") for z in elements]

    lines = ["neb_tool generated", f"{scale:.6f}"]
    for row in cell:
        lines.append(f"{row[0]:.10f} {row[1]:.10f} {row[2]:.10f}")
    lines.append(" ".join(syms))
    lines.append(" ".join(str(c) for c in counts))
    lines.append("Cartesian")
    for z in elements:
        for pos in grouped[z]:
            lines.append(f"{pos[0]:.10f} {pos[1]:.10f} {pos[2]:.10f}")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
